#!/bin/bash

git blame -L "$1,$1" "$2" \
  | while read -r commit rest; do
      msg=$(git show -s --format=%B "$commit")
      rest=$(echo $rest | sed -E 's/([^)]*\)).*/\1/')
      echo "$commit $rest | $msg"
    done

