#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <pattern> [find-options]"
  echo "Example: $0 '*.rs'     # opens all Rust files in current directory and subdirectories"
  echo "         $0 -name '*.txt'  # using find-style options"
  echo "         $0 -path \"*01-node*\" ! -path '*.png'  # using find-style options"
  exit 1
fi

# Opens all the files that match a regex in helix
files=$(find "$PWD" -type f $@ -print0 | xargs -0)

# echo "Opening ${files[@]}"

helix ${files[@]}
