theme = "ashen"

[editor]
line-number = "relative"
cursorline = true
true-color = true
preview-completion-insert = false
completion-replace = true
auto-pairs = false
bufferline = "always"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true
display-color-swatches = false
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "<->"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-r = ":rla"
q = "goto_previous_buffer"
e = "goto_next_buffer"

[editor.file-picker]
hidden = false

[editor.search]
wrap-around = false
