theme = "ashen"

[editor]
line-number = "relative"
cursorline = true
true-color = true
preview-completion-insert = false
completion-replace = true
bufferline = "always"
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true
display-color-swatches = false
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-name", "file-modification-indicator"]
right = [ "position", "separator", "version-control", "separator", "file-type"]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-r = ":rla"
q = "goto_previous_buffer"
e = "goto_next_buffer"
C-w = ":bc"
C-q = ":bco"
C-up = "page_cursor_up"
C-down = "page_cursor_down"
d = "delete_selection_noyank"
c = "change_selection_noyank"
S-up = "page_cursor_half_up"
S-down = "page_cursor_half_down"
S-m = "align_view_center"

[keys.normal.space]
d = "file_explorer_in_current_buffer_directory"

[keys.normal.space.space]
b = ":sh better-blame %{cursor_line} %{buffer_name}"
r = ":diffg"
right = ":sh send-file %{buffer_name} -R %{cursor_line}"
left = ":sh send-file %{buffer_name} -L %{cursor_line}"
down = ":sh send-file %{buffer_name} -D %{cursor_line}"
up = ":sh send-file %{buffer_name} -U %{cursor_line}"

[keys.normal.g.n]
f = "goto_next_function"
a = "goto_next_parameter"
c = "goto_next_class"
t = "goto_next_test"
p = "goto_next_paragraph"

[keys.normal.g.p]
f = "goto_prev_function"
a = "goto_prev_parameter"
c = "goto_prev_class"
t = "goto_prev_test"
p = "goto_prev_paragraph"

[editor.file-picker]
hidden = false

[editor.search]
wrap-around = false
